name: Upload to CDN

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      
      - id: 'auth'
        name: 'GCP Auth'
        uses: 'google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935' #v2.1.8
        with:
          workload_identity_provider: ${{ secrets.GH_ACTIONS_CDN_WIP }}
          service_account: ${{ secrets.GH_ACTIONS_CDN_SA }}
          export_environment_variables: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db' #v3.0.1

      - name: Change folder names to lowercase
        run: |
          find ronin/* -maxdepth 2 -type d -exec sh -c 'mv "$1" "$(dirname "$1")/$(basename "$1" | tr "[:upper:]" "[:lower:]")"' _ {} \;  

      - name: 'Upload CDN'
        run: |
          set -eo pipefail
          gsutil -m rsync -c -r ronin gs://${{ vars.CDN_BUCKET_NAME }}/ronin
